"""Core phonon unfolding classes.

Provides:

- [`Unfold`][unphold.unfold.Unfold]: general supercell → unitcell phonon band unfolding
- [`UnfoldTwistBilayer`][unphold.unfold.UnfoldTwistBilayer]: convenience wrapper for twisted bilayer systems (stub)
"""

import os
import pickle
import time

import numpy
from ase.atoms import Atoms as aseAtoms
from ase.build.supercells import make_supercell
from phonopy.harmonic.dynamical_matrix import DynamicalMatrix, DynamicalMatrixNAC
from phonopy.phonon.band_structure import BandStructure
from phonopy.physical_units import get_physical_units as _get_phonopy_units
from tqdm import tqdm

from .utils import band_expansion, match_two_atoms

_pu = _get_phonopy_units()
VaspToTHz = _pu.DefaultToTHz
VaspToEv = VaspToTHz * _pu.THzToEv
VaspToCm = VaspToTHz * _pu.THzToCm


class Unfold:
    """Unfold phonon band structure from a Phonopy supercell to a primitive unitcell.

    The spectral weight at primitive-cell k-point **k** for supercell band *n* is:

    $$w_{k,n} = \\frac{1}{N_{uc}} \\sum_i |\\langle \\phi^{uc}_{k,i} | \\Psi^{sc}_{k,n} \\rangle|^2$$

    where $N_{uc}$ is the number of primitive cells in the supercell.

    Four cases are handled depending on whether the supercell atoms need permutation
    and whether only a subset of atoms is projected (e.g. one layer of a bilayer):

    - **Case 0**: no permutation, project all atoms
    - **Case 1**: permutation required, project all atoms
    - **Case 2**: no permutation, project subset of atoms (``unfold_atoms_indices``)
    - **Case 3**: permutation + subset

    Example::

        from phonopy.phonon.band_structure import get_band_qpoints_and_path_connections
        from unphold import Unfold
        from unphold.utils import concatenate_bands

        special_points = {
            "G": [0.0, 0.0, 0.0],
            "M": [0.5, 0.5, 0.0],
            "K": [1/3, 2/3, 0.0],
        }
        bz_labels = ["G", "M", "K", "G"]
        kpath = [[special_points[l] for l in bz_labels]]
        kpts_list, connections = get_band_qpoints_and_path_connections(kpath, npoints=41)
        kpts, bz_label_indices = concatenate_bands(kpts_list, connections)

        unfold = Unfold(unitcell, supercell, tmat, verbose=True)
        unfold.set_kpts_in_unitcell(kpts, format="fractional")
        unfold.calculate_sc_phonon(ph.dynamical_matrix, "meV")
        unfold.calculate_weights()
        grid, sigma = unfold.calculate_band_expansion()
        # unfold.energies_on_grid has shape (nkpts, ngrid)
    """

    def __init__(
        self,
        unitcell: aseAtoms,
        supercell: aseAtoms,
        transformation_matrix: numpy.ndarray,
        transformation_matrix_ph: numpy.ndarray = None,
        angle: float | None = None,
        spatial_tolerance: float = 5e-2,
        unfold_atoms_indices: numpy.ndarray | None = None,
        perm_idx_i2g: numpy.ndarray | None = None,
        perm_idx_g2i: numpy.ndarray | None = None,
        verbose: bool = False,
    ):
        """
        Args:
            unitcell (aseAtoms): Primitive unitcell.
            supercell (aseAtoms): Supercell from the phonon calculation
                (retrieve via ``phonopy.unitcell`` after converting with ``atoms_ph2ase``).
            transformation_matrix (numpy.ndarray): Integer matrix mapping unitcell → supercell.
            transformation_matrix_ph (numpy.ndarray, optional): Phonopy-internal transformation
                matrix (not required by the current algorithm).
            angle (float, optional): Rotation angle in degrees to align the generated supercell
                with the Phonopy supercell (moiré systems).
            spatial_tolerance (float): Atom-matching tolerance in Angstrom.
            unfold_atoms_indices (numpy.ndarray, optional): Indices of atoms in the Phonopy
                supercell to project (e.g. one layer of a bilayer).
            perm_idx_i2g (numpy.ndarray, optional): Permutation from Phonopy supercell ordering
                to the ordering generated by ``make_supercell``.
            perm_idx_g2i (numpy.ndarray, optional): Inverse of ``perm_idx_i2g``.
            verbose (bool): Show progress bars.
        """
        self.uc = unitcell.copy()
        self.sc = supercell.copy()
        self.tmat = transformation_matrix
        self.tmat_ph = transformation_matrix_ph
        self.angle = angle
        self.sc_by_mat = None
        self.unfold_atoms_indices = unfold_atoms_indices
        self.perm_idx_i2g = perm_idx_i2g
        self.perm_idx_g2i = perm_idx_g2i
        self.spa_tol = spatial_tolerance
        self.verbose = verbose
        self.prepare()

    def __repr__(self):
        return (
            f"Unfold(uc={self.uc.symbols}, sc={self.sc.symbols}, tmat={self.tmat}, "
            f"angle={self.angle}, spa_tol={self.spa_tol:.2e}, "
            f"unfold_atoms_indices={self.unfold_atoms_indices})"
        )

    def prepare(self):
        """Validate geometry and precompute lattice/BZ vectors.

        Called automatically on construction. Re-call if you modify ``tmat`` or ``angle``.

        Relations::

            sc_lattice = tmat @ uc_lattice
            uc_BZ      = tmat.T @ sc_BZ
        """
        self.sc_by_mat = make_supercell(self.uc, self.tmat, wrap=False)
        if self.angle is not None:
            assert isinstance(self.angle, float)
            self.sc_by_mat.rotate(self.angle, "z", rotate_cell=True)

        if (self.perm_idx_g2i is not None) and (self.perm_idx_i2g is not None):
            assert isinstance(self.perm_idx_g2i, numpy.ndarray)
            assert isinstance(self.perm_idx_i2g, numpy.ndarray)
            assert self.perm_idx_g2i.shape == self.perm_idx_i2g.shape
            assert numpy.all(self.perm_idx_g2i >= 0) and numpy.all(self.perm_idx_i2g >= 0)
            if self.unfold_atoms_indices is None:
                assert len(self.perm_idx_g2i) == len(self.sc_by_mat)
                assert len(self.perm_idx_i2g) == len(self.uc)
            else:
                assert len(self.perm_idx_g2i) == len(self.unfold_atoms_indices)
                assert len(self.perm_idx_i2g) == len(self.unfold_atoms_indices)
                assert len(self.unfold_atoms_indices) == len(self.sc_by_mat)
                assert len(numpy.unique(self.unfold_atoms_indices)) == len(self.unfold_atoms_indices)
        else:
            print("WARNING: it is strongly recommended to provide permutation indices perm_idx_i2g and perm_idx_g2i")
            _match = match_two_atoms(self.sc, self.sc_by_mat, spatial_tolerance=self.spa_tol)
            if _match["fail_reason"] is not None:
                raise ValueError(_match["fail_reason"])
            self.perm_idx_i2g = _match["atoms_indices_a2b"]
            self.perm_idx_g2i = _match["atoms_indices_b2a"]

        self.nucs_in_sc = len(self.sc_by_mat) // len(self.uc)

        self.uc_la = numpy.array(self.uc.cell)
        self.uc_bz = numpy.array(self.uc.cell.reciprocal())
        self.sc_la = numpy.array(self.sc.cell)
        self.sc_bz = numpy.array(self.sc.cell.reciprocal())
        assert numpy.allclose(self.sc_la[:2, :2], (self.tmat @ self.uc_la)[:2, :2], atol=3e-2)
        assert numpy.allclose(self.uc_bz[:2, :2], (self.tmat.T @ self.sc_bz)[:2, :2], atol=3e-2)

    def set_kpts_in_unitcell(
        self,
        kpts: numpy.ndarray,
        format: str = "fractional",
    ):
        """Set the k-points to evaluate, given in the primitive-cell BZ.

        Cartesian coordinates are without the 2π prefactor (i.e. in units of Å⁻¹).

        Args:
            kpts (numpy.ndarray): K-points, shape ``(nkpts, 3)``.
            format (str): ``"fractional"`` (default) or ``"cartesian"``.
        """
        if format == "fractional":
            self.kpts_cart = numpy.matmul(kpts, self.uc_bz)
            self.kpts_uc_frac = kpts
            self.kpts_sc_frac = numpy.matmul(self.kpts_uc_frac, self.tmat.T)
        elif format == "cartesian":
            self.kpts_cart = kpts
            self.kpts_uc_frac = numpy.matmul(kpts, numpy.linalg.inv(self.uc_bz))
            self.kpts_sc_frac = numpy.matmul(kpts, numpy.linalg.inv(self.sc_bz))
        else:
            raise ValueError(f"format={format!r} not supported")
        assert numpy.allclose(self.kpts_uc_frac @ self.uc_bz, self.kpts_cart)
        assert numpy.allclose(self.kpts_sc_frac @ self.sc_bz, self.kpts_cart)

    def calculate_sc_phonon(
        self,
        dyn_sc: DynamicalMatrix | DynamicalMatrixNAC,
        factor: float | str = VaspToEv,
        save_fpath: str | None = None,
    ):
        """Diagonalise the supercell dynamical matrix along the set k-path.

        This is the most expensive step. Progress cannot be tracked because it is
        internal to Phonopy.

        Args:
            dyn_sc: Dynamical matrix from ``phonopy.dynamical_matrix``.
            factor (float or str): Energy unit conversion. Strings: ``"ev"``, ``"mev"``,
                ``"thz"``, ``"cm"``. Default: ``VaspToEv``.
            save_fpath (str, optional): Path to save results as ``.npz``.
        """
        if isinstance(factor, float):
            pass
        elif isinstance(factor, str):
            factor = factor.lower()
            assert factor in ("ev", "mev", "thz", "cm"), f"factor={factor!r} not supported"
            factor = {"ev": VaspToEv, "mev": VaspToEv * 1e3, "thz": VaspToTHz, "cm": VaspToCm}[factor]
        else:
            raise ValueError(f"factor={factor!r} not supported")

        time_start = time.time()
        bs_sc = BandStructure(
            paths=[self.kpts_sc_frac],
            dynamical_matrix=dyn_sc,
            with_eigenvectors=True,
            factor=factor,
        )
        time_end = time.time()
        self.bs_sc_energies = bs_sc.frequencies[0]
        self.bs_sc_eigenvecs = bs_sc.eigenvectors[0]
        print(
            f"Band structure: {time_end - time_start:.2f}s for {len(self.kpts_sc_frac)} k-points "
            f"({(time_end - time_start) / len(self.kpts_sc_frac):.3f}s/k-point)."
        )
        if save_fpath is not None:
            if not save_fpath.endswith(".npz"):
                print("WARNING: save_fpath should end with .npz — appending.")
                save_fpath += ".npz"
            os.makedirs(os.path.dirname(save_fpath), exist_ok=True)
            numpy.savez(
                file=save_fpath,
                bs_sc_energies=bs_sc.frequencies[0],
                bs_sc_eigenvecs=bs_sc.eigenvectors[0],
                kpts_sc_frac=self.kpts_sc_frac,
                factor=factor,
            )

    def load_sc_phonon(self, save_fpath: str) -> float:
        """Load a previously saved supercell phonon band structure.

        Args:
            save_fpath (str): Path to the ``.npz`` file written by :meth:`calculate_sc_phonon`.

        Returns:
            float: The energy conversion factor used when the file was saved.
        """
        assert os.path.exists(save_fpath), f"File {save_fpath} does not exist."
        data = numpy.load(save_fpath, allow_pickle=True)
        assert data["bs_sc_energies"].shape[0] == self.kpts_sc_frac.shape[0]
        assert data["bs_sc_energies"].shape[1] == len(self.sc) * 3
        assert data["bs_sc_eigenvecs"].shape[1] == len(self.sc) * 3
        self.bs_sc_energies = data["bs_sc_energies"]
        self.bs_sc_eigenvecs = data["bs_sc_eigenvecs"]
        assert numpy.allclose(self.kpts_sc_frac, data["kpts_sc_frac"])
        return float(data["factor"])

    def _calculate_weights_one_kpt(self, kpt_idx: int) -> numpy.ndarray:
        uc_natoms = len(self.uc)
        sc_natoms = len(self.sc)
        sc_uf_natoms = len(self.unfold_atoms_indices) if self.unfold_atoms_indices is not None else sc_natoms

        uc_modes = numpy.diag(numpy.ones(3 * uc_natoms)).reshape(uc_natoms, 3, 3 * uc_natoms)
        uc2sc_modes = numpy.tile(uc_modes, (self.nucs_in_sc, 1, 1))

        if self.perm_idx_g2i is not None:
            uc2sc_modes = uc2sc_modes[self.perm_idx_g2i]
            uc2sc_modes = uc2sc_modes.reshape(3 * len(self.perm_idx_g2i), 3 * uc_natoms)
        else:
            uc2sc_modes = uc2sc_modes.reshape(3 * sc_natoms, 3 * uc_natoms)

        sc_modes = self.bs_sc_eigenvecs[kpt_idx]

        if self.unfold_atoms_indices is not None:
            sc_uf_modes = sc_modes.reshape(sc_natoms, 3, 3 * sc_natoms)
            sc_uf_modes = sc_uf_modes[self.unfold_atoms_indices]
            sc_uf_modes = sc_uf_modes.reshape(3 * sc_uf_natoms, 3 * sc_natoms)
            weights = numpy.einsum("in,ib->nb", uc2sc_modes.conj(), sc_uf_modes)
            weights = (numpy.abs(weights) ** 2).sum(axis=0)
        else:
            weights = numpy.einsum("in,ib->nb", uc2sc_modes.conj(), sc_modes)
            weights = (numpy.abs(weights) ** 2).sum(axis=0)

        return weights / self.nucs_in_sc

    def calculate_weights(self):
        """Calculate spectral weights for all k-points.

        Results are stored in ``self.weights``, shape ``(nkpts, sc_nbands)``.
        """
        weights = []
        iterator = (
            tqdm(range(len(self.kpts_uc_frac)), desc="Projecting", ncols=119)
            if self.verbose
            else range(len(self.kpts_uc_frac))
        )
        for kpt_idx in iterator:
            weights.append(self._calculate_weights_one_kpt(kpt_idx))
        self.weights = numpy.array(weights)

    def _calulate_band_expansion_one_kpt(
        self,
        kpt_idx: int,
        grid: numpy.ndarray,
        sigma: float,
    ) -> numpy.ndarray:
        weights = self.weights[kpt_idx]
        sc_energies = self.bs_sc_energies[kpt_idx]
        sc_energies_expanded = band_expansion(energies=sc_energies, grid=grid, sigma=sigma)
        return numpy.einsum("j,jk->k", weights, sc_energies_expanded)

    def calculate_band_expansion(
        self,
        grid: numpy.ndarray | None = None,
        sigma: float | None = None,
    ) -> tuple:
        """Project weighted supercell bands onto an energy grid.

        If ``grid`` and ``sigma`` are None, sensible defaults are chosen automatically
        from the range of ``bs_sc_energies``.

        Args:
            grid (numpy.ndarray, optional): 1D energy grid.
            sigma (float, optional): Gaussian broadening width (same units as energies).

        Returns:
            tuple: ``(grid, sigma)`` — the grid and broadening used.

        After calling, ``self.energies_on_grid`` has shape ``(nkpts, ngrid)``.
        """
        if grid is None and sigma is None:
            _div = (self.bs_sc_energies.max() - self.bs_sc_energies.min()) / 2000
            _overshoot = self.bs_sc_energies.max() * 0.05
            grid = numpy.arange(
                self.bs_sc_energies.min() - _overshoot,
                self.bs_sc_energies.max() + _overshoot,
                _div,
            )
            sigma = 5 * _div
        else:
            assert isinstance(grid, numpy.ndarray) and grid.ndim == 1
            assert isinstance(sigma, float) and sigma > 0

        iterator = (
            tqdm(range(len(self.kpts_uc_frac)), desc="Building Grids", ncols=119)
            if self.verbose
            else range(len(self.kpts_uc_frac))
        )
        energies_on_grid = []
        for kpt_idx in iterator:
            energies_on_grid.append(self._calulate_band_expansion_one_kpt(kpt_idx, grid, sigma))
        self.energies_on_grid = numpy.stack(energies_on_grid, axis=0)
        return grid, sigma

    def save(self, fpath: str):
        """Serialise the Unfold object to disk (pickle).

        Args:
            fpath (str): Output path.
        """
        with open(fpath, "wb") as f:
            pickle.dump(self, f)

    @classmethod
    def load(cls, fpath: str) -> "Unfold":
        """Load a serialised Unfold object.

        Args:
            fpath (str): Path written by :meth:`save`.

        Returns:
            Unfold: Deserialised object.

        Raises:
            TypeError: If the loaded object is not an Unfold instance.
        """
        with open(fpath, "rb") as f:
            loaded_obj = pickle.load(f)
        if not isinstance(loaded_obj, cls):
            raise TypeError(f"Loaded object is not an instance of {cls.__name__}")
        return loaded_obj


class UnfoldTwistBilayer:
    """Convenience wrapper for unfolding phonons in twisted bilayer systems.

    Handles the geometry setup (twist angle, layer selection, permutation)
    automatically, so the user only needs to provide the two monolayer unitcells
    and the twist angle.

    Note:
        This class is a stub. Implementation is in progress.
        Use [`Unfold`][unphold.unfold.Unfold] directly with explicit `unfold_atoms_indices`
        and permutation arguments in the meantime.
    """

    def __init__(self):
        raise NotImplementedError(
            "UnfoldTwistBilayer is not yet implemented. Use Unfold directly with unfold_atoms_indices."
        )
